name: Package

on:
  push:
    branches:
      - master
      - dev-workflow
  pull_request:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  metadata:
    name: Get metadata
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Version
        id: version
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
          else
            echo "version=devel" >> "$GITHUB_OUTPUT"
          fi

  debian:
    name: Build debian package
    runs-on: ubuntu-24.04
    needs: metadata
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@a809471b5c7c913aa67bec8f459a11a0decc3fce # v31
      - name: Build
        run: nix-shell --run 'build_deb_package'

      - name: Archive package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: my-lib-${{ needs.metadata.outputs.version }}_deb
          path: |
            ${{ github.workspace }}/out/deb_package/*.deb
            ${{ github.workspace }}/out/deb_package/*.deb.sha512
      - name: Upload to release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: xresloader/upload-to-github-release@e6ac9c2ff1018fca4464bf2480155faeb66f9bdb  # v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ github.workspace }}/out/deb_package/*.deb;${{ github.workspace }}/out/deb_package/*.deb.sha512"
          tags: true

  rpm:
    name: Build rpm package
    runs-on: ubuntu-24.04
    needs: metadata
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@a809471b5c7c913aa67bec8f459a11a0decc3fce # v31
      - name: Build
        run: nix-shell --run 'build_rpm_package'

      - name: Archive package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: my-lib-${{ needs.metadata.outputs.version }}_rpm
          path: |
            ${{ github.workspace }}/out/rpm_package/*.rpm
            ${{ github.workspace }}/out/rpm_package/*.rpm.sha512
      - name: Upload to release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: xresloader/upload-to-github-release@e6ac9c2ff1018fca4464bf2480155faeb66f9bdb  # v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ github.workspace }}/out/rpm_package/*.rpm;${{ github.workspace }}/out/rpm_package/*.rpm.sha512"
          tags: true

  nix:
    name: Build nix package
    runs-on: ubuntu-24.04
    needs: metadata
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@a809471b5c7c913aa67bec8f459a11a0decc3fce # v31
      - name: Build
        run: nix-build ${{ github.workspace }}/tools/nix -A my_lib
