name: Package

on:
  push:
    branches:
      - master
      - dev-workflow
  pull_request:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  metadata:
    name: Get metadata
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Version
        id: version
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
          else
            echo "version=devel" >> "$GITHUB_OUTPUT"
          fi

  debian:
    name: Build debian package
    runs-on: ubuntu-24.04
    needs: metadata
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - name: Build
        run: nix-shell --run 'build_deb_package'

      - name: Archive package
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: filc-${{ needs.metadata.outputs.version }}_deb
          path: |
            ${{ github.workspace }}/out/deb_package/*.deb
            ${{ github.workspace }}/out/deb_package/*.deb.sha512
      - name: Upload to release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: xresloader/upload-to-github-release@26f7cc1d7d924dc9b6d5008808be8278b7177811  # v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ github.workspace }}/out/deb_package/*.deb;${{ github.workspace }}/out/deb_package/*.deb.sha512"
          tags: true

  rpm:
    name: Build rpm package
    runs-on: ubuntu-24.04
    needs: metadata
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - name: Build
        run: nix-shell --run 'build_rpm_package'

      - name: Archive package
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: filc-${{ needs.metadata.outputs.version }}_rpm
          path: |
            ${{ github.workspace }}/out/rpm_package/*.rpm
            ${{ github.workspace }}/out/rpm_package/*.rpm.sha512
      - name: Upload to release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: xresloader/upload-to-github-release@26f7cc1d7d924dc9b6d5008808be8278b7177811  # v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "${{ github.workspace }}/out/rpm_package/*.rpm;${{ github.workspace }}/out/rpm_package/*.rpm.sha512"
          tags: true
